import test from 'node:test';
import assert from 'node:assert/strict';
import {handle,seal,unseal} from '../lib/relay.js';
process.env.TESLA_CLIENT_ID='test-client';process.env.TESLA_CLIENT_SECRET='test-secret-only';process.env.TESLA_SETUP_KEY='test-only-protection-key-at-least-32-characters';
const host='tesla-oauth-relay.vercel.app',origin='https://'+host;
function response(){return {headers:{},setHeader(n,v){this.headers[n]=v;},getHeader(n){return this.headers[n];},end(b=''){this.body=b;}};}
const auth=()=>`__Host-admin=${seal('admin',true,100)}`;
test('encrypted cookies reject changes, purpose substitution and expiry',()=>{const x=seal('refresh','fake-refresh-token',60);assert.ok(!x.includes('fake-refresh-token'));assert.equal(unseal('refresh',x),'fake-refresh-token');assert.equal(unseal('admin',x),null);assert.equal(unseal('refresh',x.slice(0,-4)+'AAAA'),null);assert.equal(unseal('refresh',seal('refresh','expired',-1)),null);});
test('setup and vehicle data require owner login',async()=>{for(const action of ['setup','vehicles','state']){const r=response();await handle(action,{method:'POST',headers:{host,origin},body:{}},r);assert.equal(r.statusCode,401);assert.ok(!r.headers['Set-Cookie']);}});
test('cross-origin requests and wrong production host fail closed',async()=>{for(const headers of [{host,origin:'https://attacker.example',cookie:auth()},{host:'preview.example',origin,cookie:auth()}]){const r=response();await handle('setup',{method:'POST',headers,body:{}},r);assert.equal(r.statusCode,403);}});
test('OAuth state mismatch never exchanges a code',async()=>{const r=response();await handle('callback',{method:'GET',url:'/api/callback?state=wrong&code=private-code',headers:{host,cookie:auth()+'; __Host-oauth='+seal('oauth',{state:'expected'},100)}},r);assert.equal(r.headers.Location,'/?error=oauth_state_invalid');assert.ok(!r.body.includes('private-code'));});
test('authorization requests have only required read scopes',async()=>{const r=response();await handle('connect',{method:'POST',headers:{host,origin,cookie:auth()},body:{}},r);const u=new URL(JSON.parse(r.body).url);assert.equal(u.searchParams.get('redirect_uri'),origin+'/api/callback');assert.equal(u.searchParams.get('scope'),'openid offline_access vehicle_device_data vehicle_location');assert.equal(u.searchParams.has('client_secret'),false);});
test('partner token is correctly form encoded; secrets never returned',async()=>{const old=global.fetch;const calls=[];global.fetch=async(url,options)=>{calls.push({url,options});if(url.endsWith('.pem'))return {ok:true,text:async()=> (await import('../lib/key.js')).default};if(url.endsWith('/token'))return {ok:true,json:async()=>({access_token:'fake-partner-token'})};if(url.includes('/public_key?'))return {ok:true,json:async()=>({response:{public_key:(await import('../lib/key.js')).default}})};return {ok:true,json:async()=>({response:{}})};};try{const r=response();await handle('setup',{method:'POST',headers:{host,origin,cookie:auth()},body:{}},r);assert.equal(r.statusCode,200);const t=calls.find(c=>c.url.endsWith('/token'));assert.equal(t.options.body.get('client_id'),'test-client');assert.equal(t.options.body.get('grant_type'),'client_credentials');assert.equal(t.options.body.get('audience'),'https://fleet-api.prd.eu.vn.cloud.tesla.com');assert.ok(!r.body.includes('fake-partner-token'));assert.ok(!r.body.includes('test-secret'));}finally{global.fetch=old;}});
test('callback stores opaque HttpOnly tokens and redirects without secrets',async()=>{const old=global.fetch;global.fetch=async()=>({ok:true,json:async()=>({access_token:'fake-access',refresh_token:'fake-refresh',expires_in:3600})});try{const r=response();await handle('callback',{method:'GET',url:'/api/callback?state=expected&code=private-code',headers:{host,cookie:auth()+'; __Host-oauth='+seal('oauth',{state:'expected'},100)}},r);assert.equal(r.headers.Location,'/?connected=1');for(const c of r.headers['Set-Cookie']){assert.ok(c.includes('Secure; HttpOnly'));assert.ok(!c.includes('fake-access'));assert.ok(!c.includes('fake-refresh'));}assert.equal(r.body,'');}finally{global.fetch=old;}});
