import {createHash,createCipheriv,createDecipheriv,randomBytes,timingSafeEqual,createPublicKey} from 'node:crypto';
import publicKey from './key.js';
const ORIGIN='https://tesla-oauth-relay.vercel.app';
const FLEET='https://fleet-api.prd.eu.vn.cloud.tesla.com';
const TOKEN='https://fleet-auth.prd.vn.cloud.tesla.com/oauth2/v3/token';
const SCOPE='openid offline_access vehicle_device_data vehicle_location';
export class SafeError extends Error {constructor(status,code){super(code);this.status=status;}}
const fail=(s,c)=>{throw new SafeError(s,c);};
function configured(){if(!process.env.TESLA_CLIENT_ID?.trim()||!process.env.TESLA_CLIENT_SECRET||process.env.TESLA_SETUP_KEY?.length<32||!process.env.TESLA_SETUP_KEY)fail(503,'setup_required');}
const digest=x=>createHash('sha256').update(x).digest();
const equal=(a,b)=>typeof a==='string'&&typeof b==='string'&&timingSafeEqual(digest(a),digest(b));
function encryptionKey(){configured();return digest('tesla-relay-v2\0'+process.env.TESLA_CLIENT_SECRET+'\0'+process.env.TESLA_SETUP_KEY);}
export function seal(name,value,seconds){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',encryptionKey(),iv);c.setAAD(Buffer.from(name));const ciphertext=Buffer.concat([c.update(JSON.stringify({value,until:Date.now()+seconds*1000})),c.final()]);return Buffer.concat([iv,c.getAuthTag(),ciphertext]).toString('base64url');}
export function unseal(name,raw){try{if(!raw||raw.length>3800)return null;const b=Buffer.from(raw,'base64url');const d=createDecipheriv('aes-256-gcm',encryptionKey(),b.subarray(0,12));d.setAAD(Buffer.from(name));d.setAuthTag(b.subarray(12,28));const p=JSON.parse(Buffer.concat([d.update(b.subarray(28)),d.final()]));return p.until>Date.now()?p.value:null;}catch{return null;}}
function readCookie(req,name){const prefix='__Host-'+name+'=';const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(prefix));return unseal(name,raw?.slice(prefix.length));}
function cookie(res,name,value,seconds){const raw=seconds?seal(name,value,seconds):'';if(raw.length>3800)fail(502,'token_storage_too_large');const prior=res.getHeader('Set-Cookie')||[];res.setHeader('Set-Cookie',[...prior,`__Host-${name}=${raw}; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=${seconds}`]);}
function admin(req){if(!readCookie(req,'admin'))fail(401,'login_required');}
function post(req){if(req.method!=='POST')fail(405,'method_not_allowed');if(req.headers.origin!==ORIGIN)fail(403,'origin_rejected');}
function json(res,value,status=200){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(value));}
function redirect(res,url){res.statusCode=303;res.setHeader('Location',url);res.end();}
async function request(url,options={}){const r=await fetch(url,{...options,redirect:'error',signal:AbortSignal.timeout(20000)});let body;try{body=await r.json();}catch{fail(502,'invalid_upstream_response');}if(!r.ok){const allowed=['unauthorized_client','invalid_client','invalid_auth_code','login_required','invalid_grant','invalid_scope','invalid_request'];const code=allowed.includes(body.error)?body.error:'upstream_http_'+r.status;fail(r.status===401?401:502,code);}return body;}
async function token(fields){return request(TOKEN,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(fields)});}
function saveTokens(res,t){if(typeof t.access_token!=='string'||typeof t.refresh_token!=='string'||!Number.isFinite(Number(t.expires_in))||Number(t.expires_in)<=0)fail(502,'invalid_token_response');cookie(res,'access',{token:t.access_token,expires:Date.now()+Number(t.expires_in)*1000},86400);cookie(res,'refresh',t.refresh_token,90*86400);}
async function userToken(req,res){const a=readCookie(req,'access');if(a?.expires>Date.now()+60000)return a.token;const r=readCookie(req,'refresh');if(!r)fail(401,'tesla_login_required');const t=await token({grant_type:'refresh_token',client_id:process.env.TESLA_CLIENT_ID.trim(),refresh_token:r});saveTokens(res,t);return t.access_token;}
function normalizeKey(value){if(typeof value!=='string')fail(502,'public_key_verification_failed');if(value.includes('BEGIN PUBLIC KEY'))return createPublicKey(value).export({format:'der',type:'spki'});if(/^04[0-9a-f]{128}$/i.test(value)){const raw=Buffer.from(value,'hex');return createPublicKey({key:{kty:'EC',crv:'P-256',x:raw.subarray(1,33).toString('base64url'),y:raw.subarray(33).toString('base64url')},format:'jwk'}).export({format:'der',type:'spki'});}return createPublicKey({key:Buffer.from(value,'base64'),format:'der',type:'spki'}).export({format:'der',type:'spki'});}
async function setup(){const hosted=await fetch(ORIGIN+'/.well-known/appspecific/com.tesla.3p.public-key.pem',{redirect:'error',signal:AbortSignal.timeout(10000)});if(!hosted.ok)fail(502,'public_key_not_hosted');const expected=normalizeKey(publicKey);if(!normalizeKey(await hosted.text()).equals(expected))fail(502,'hosted_public_key_mismatch');const p=await token({grant_type:'client_credentials',client_id:process.env.TESLA_CLIENT_ID.trim(),client_secret:process.env.TESLA_CLIENT_SECRET,audience:FLEET});if(typeof p.access_token!=='string')fail(502,'partner_token_missing');const headers={Authorization:'Bearer '+p.access_token,'Content-Type':'application/json'};await request(FLEET+'/api/1/partner_accounts',{method:'POST',headers,body:JSON.stringify({domain:new URL(ORIGIN).hostname})});const check=await request(FLEET+'/api/1/partner_accounts/public_key?domain='+new URL(ORIGIN).hostname,{headers});const returned=check.response?.public_key??check.public_key??(typeof check.response==='string'?check.response:null);if(!normalizeKey(returned).equals(expected))fail(502,'registered_public_key_mismatch');return {registered:true,publicKeyVerified:true,region:'EU'};}
export async function handle(action,req,res){res.setHeader('Cache-Control','no-store, private');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Content-Type-Options','nosniff');try{
  if(req.headers.host!==new URL(ORIGIN).hostname)fail(403,'production_host_required');
  if(action==='config'){if(req.method!=='GET')fail(405,'method_not_allowed');return json(res,{configured:!!(process.env.TESLA_CLIENT_ID&&process.env.TESLA_CLIENT_SECRET&&process.env.TESLA_SETUP_KEY?.length>=32),admin:!!readCookie(req,'admin'),teslaConnected:!!readCookie(req,'refresh'),callback:ORIGIN+'/api/callback',scopes:SCOPE});}
  configured();
  if(action==='login'){post(req);if(!equal(req.body?.key,process.env.TESLA_SETUP_KEY))fail(401,'login_failed');cookie(res,'admin',true,8*3600);return json(res,{ok:true});}
  admin(req);
  if(action==='logout'){post(req);for(const n of ['admin','access','refresh','oauth'])cookie(res,n,null,0);return json(res,{ok:true});}
  if(action==='setup'){post(req);return json(res,await setup());}
  if(action==='connect'){post(req);const state=randomBytes(32).toString('base64url');cookie(res,'oauth',{state},600);const url=new URL('https://auth.tesla.com/oauth2/v3/authorize');url.search=new URLSearchParams({client_id:process.env.TESLA_CLIENT_ID.trim(),redirect_uri:ORIGIN+'/api/callback',response_type:'code',scope:SCOPE,state,locale:'hu-HU',prompt_missing_scopes:'true',require_requested_scopes:'true'}).toString();return json(res,{url:url.toString()});}
  if(action==='callback'){if(req.method!=='GET')fail(405,'method_not_allowed');const u=new URL(req.url,ORIGIN),saved=readCookie(req,'oauth');cookie(res,'oauth',null,0);if(!saved||!equal(u.searchParams.get('state'),saved.state))fail(400,'oauth_state_invalid');if(u.searchParams.has('error'))fail(400,'tesla_authorization_declined');const code=u.searchParams.get('code');if(!code||code.length>4096)fail(400,'authorization_code_missing');const t=await token({grant_type:'authorization_code',client_id:process.env.TESLA_CLIENT_ID.trim(),client_secret:process.env.TESLA_CLIENT_SECRET,audience:FLEET,redirect_uri:ORIGIN+'/api/callback',code});saveTokens(res,t);return redirect(res,'/?connected=1');}
  post(req);const access=await userToken(req,res);const headers={Authorization:'Bearer '+access};
  if(action==='vehicles'){const data=await request(FLEET+'/api/1/vehicles',{headers});return json(res,{vehicles:(data.response||[]).map(v=>({vin:v.vin,name:v.display_name,state:v.state,locationAllowed:v.granular_access?.hide_private!==true}))});}
  if(action==='state'){const vin=req.body?.vin;if(typeof vin!=='string'||!/^\w{17}$/.test(vin))fail(400,'invalid_vin');const summary=await request(FLEET+'/api/1/vehicles/'+encodeURIComponent(vin),{headers});if(summary.response?.state!=='online')return json(res,{state:summary.response?.state||'unknown',liveDataAvailable:false});const data=await request(FLEET+'/api/1/vehicles/'+encodeURIComponent(vin)+'/vehicle_data?endpoints=charge_state%3Bclimate_state%3Bvehicle_state%3Bdrive_state%3Blocation_data',{headers});const v=data.response||{};return json(res,{fetchedAt:new Date().toISOString(),state:'online',batteryPercent:v.charge_state?.battery_level,chargingState:v.charge_state?.charging_state,rangeKm:v.charge_state?.battery_range==null?null:Math.round(v.charge_state.battery_range*1.609344),locked:v.vehicle_state?.locked,insideC:v.climate_state?.inside_temp,outsideC:v.climate_state?.outside_temp,latitude:v.location_data?.latitude??v.drive_state?.latitude,longitude:v.location_data?.longitude??v.drive_state?.longitude,vehicleTimestamp:v.drive_state?.timestamp??v.location_data?.timestamp,liveDataAvailable:true});}
  fail(404,'not_found');
}catch(e){const code=e instanceof SafeError?e.message:'request_failed';if(action==='callback')return redirect(res,'/?error='+encodeURIComponent(code));return json(res,{error:code},e instanceof SafeError?e.status:502);}}
